# Generated by Django 3.1.4 on 2021-05-28 01:13

from django.db import migrations

from accounts.models import User


def create_admin(apps, schema_editor):
    user = User(username='admin', email='admin@admin.com')
    user.is_superuser = True
    user.is_active = True
    user.is_staff = True
    user.set_password('admin123')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210524_2255'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
