# Generated by Django 3.1.4 on 2021-05-25 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=25, verbose_name='CEP')),
                ('address', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('city', models.CharField(max_length=250, verbose_name='Cidade')),
                ('state', models.CharField(max_length=150, verbose_name='Estado')),
                ('country', models.CharField(max_length=150, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('finish', 'Finalizada')], max_length=20, verbose_name='Status')),
                ('date_open', models.DateField(default=django.utils.timezone.now, verbose_name='Data de abertura')),
                ('date_finish', models.DateField(blank=True, default=None, null=True, verbose_name='Data de finalização')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demands_address', to='demands.address', verbose_name='Endereço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
