# Generated by Django 3.1.4 on 2021-05-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210524_2255'),
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands_user', to='accounts.profile', verbose_name='Usuário'),
        ),
    ]
