# Generated by Django 3.1.4 on 2021-05-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demands',
            options={'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.AlterField(
            model_name='demands',
            name='date_finish',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de finalização'),
        ),
    ]
