# Generated by Django 3.1.4 on 2021-05-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_auto_20210527_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('finish', 'Finalizada')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
